<script type="text/javascript">


    function delete_validation(id) {
        if (confirm('<?php echo $this->translate('checkDeleteValidation') ?>')) {
            window.location.href = '<?php echo APPLICATION_URL;?>validation/delete/validationId/' + id + '/';
        }
        return false;
    }

    function match_validation(id) {
        if (confirm('<?php echo $this->translate('checkMatchValidation') ?>')) {
            window.location.href = '<?php echo APPLICATION_URL;?>validation/match/validationId/' + id + '/';
        }
        return false;
    }

</script>


<h1 class="pageName"><?php echo $this->translate('validation') ?></h1>
<div class="numberResult">
    (<?php echo $this->translate('numberOfResults') ?> <?php echo($this->paginator->getTotalItemCount()) ?>)
</div>

<?php if (count($this->paginator)): ?>
    <table class="list" cellpadding="0" cellspacing="0" width="100%">
        <tr class="headline">
            <th>
                <?php $urlDirection = ($this->direction == "ASC") ? "DESC" : "ASC"; ?>
                <a class="link" href="<?php echo $this->url(array('orderBy' => Db_ImportFileValidation::CREATED, 'direction' => (($this->orderBy == Db_ImportFileValidation::CREATED) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('created'); ?>
                </a>
            </th>
            <th>
                <a class="link" href="<?php echo $this->url(array('orderBy' => Db_ImportFileValidation::TYPE, 'direction' => (($this->orderBy == Db_ImportFileValidation::TYPE) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('type'); ?>
                </a>
            </th>
            <th>
                <a class="link" href="<?php echo $this->url(array('orderBy' => Db_ImportFileValidation::NAME, 'direction' => (($this->orderBy == Db_ImportFileValidation::NAME) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('name'); ?>
                </a>
            </th>
            <th style="width:300px;">&nbsp;</th>
        </tr>
        <?php
        $row_count = 0;
        foreach ($this->paginator as $item):
            ?>
            <tr class="<?php echo $item[Db_ImportFileValidation::TYPE]; ?>">
                <td>
                    <a href="<?php echo APPLICATION_URL; ?>validation/detail/validationId/<?php echo $item[Db_ImportFileValidation::ID]; ?>/type/<?php echo $item[Db_ImportFileValidation::TYPE]; ?>"><?php echo $item[Db_ImportFileValidation::CREATED]; ?></a>
                </td>
                <td><?php echo $item[Db_ImportFileValidation::TYPE]; ?></td>
                <td><?php echo $item[Db_ImportFileValidation::NAME]; ?></td>
                <td>
                    <a class="delete_list" onclick="javascript:delete_validation(<?php echo $item[Db_ImportFileValidation::ID] ?>)" title="<?php echo $this->translate('delete') ?>" href="#"></a>
                    <div class="rfloater">
                        <a class="link  buttonLink" onclick="javascript:match_validation(<?php echo $item[Db_ImportFileValidation::ID] ?>)" href="#"><?php echo $this->translate('match') ?></a>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?php echo $this->paginator; ?>
<?php else: ?>
    <div class="empty_message">
        <?php echo $this->translate('noValidationFound') ?>
    </div>
<?php endif; ?>