<a class="button overview" href="<?php echo APPLICATION_URL ?>searchlist/index"><?php echo $this->translate('back') ?></a>
<h1 class="pageName"><?php echo $this->translate('searchListCreateForCiType') ?><?php echo $this->ciTypeId ?></h1>

<form name="<?php echo $this->escape($this->form->getName()) ?>" action="<?php echo $this->escape($this->form->getAction()) ?>"
      method="<?php echo $this->escape($this->form->getMethod()) ?>">

    <fieldset class="lordVader">

        <table style="margin-bottom:15px;">
            <tr>
                <td><label><?php echo $this->translate('scrollable') ?>: </label></td>
                <td><?php echo $this->form->scrollable ?></td>
            </tr>
        </table>
        <table>
            <tr>
                <th>
                <?php echo $this->translate('position') ?></td>
                <th>
                <?php echo $this->translate('attribute') ?></td>
                <th>
                <?php echo $this->translate('width'); ?></td>
            </tr>

            <?php for ($i = 1; $i <= $this->maxElements; $i++) { ?>
                <tr>
                    <td><?php echo $this->translate('position') ?> <?php echo $i ?>:</td>
                    <td><?php $elem = 'create_' . $i;
                        echo $this->form->$elem ?></td>
                    <td><?php $elem = 'width_' . $i;
                        echo $this->form->$elem ?></td>
                </tr>
            <?php } ?>
        </table>
        <?php echo $this->form->save ?>
</form>
</fieldset>
