<script type="text/javascript">
    function delete_theme(id) {
        if (confirm('<?php echo $this->translate("areYouSureClose"); ?>')) {
            window.location.href = '<?php echo APPLICATION_URL?>ticket/delete/ciTicketId/' + id + '/';
        }
    }
</script>

<h1 class="pageName"><?php echo $this->translate('ticketTitle'); ?></h1>
<div class="numberResult">
    (<?php echo $this->translate('numberOfResults') ?> <?php echo($this->paginator->getTotalItemCount()) ?>)
</div>

<div id="filter">
    <div class="filter-box">
        <form name="<?php echo $this->escape($this->searchForm->getName()) ?>"
              action="<?php echo $this->escape($this->searchForm->getAction()) ?>"
              method="<?php echo $this->escape($this->searchForm->getMethod()) ?>">
            <?php
            echo $this->searchForm->search->setDecorators(array('Errors', array('ViewHelper', array('tag' => '<div>'))));
            echo $this->searchForm->filterTickets;
            ?>
        </form>
    </div>
</div>
<div class="clearBoth" style="margin-bottom: 15px;"></div>

<?php if (count($this->paginator)): ?>

<table class="list" cellpadding="0" cellspacing="0" width="100%">
    <tr class="headline">
        <th>
            <?php $urlDirection = ($this->direction == "ASC") ? "DESC" : "ASC"; ?>
            <a class="link" href="<?php echo $this->url(array('orderBy' => Db_CiTicket::TICKET_ID, 'direction' => (($this->orderBy == Db_CiTicket::TICKET_ID) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                <?php echo $this->translate('ticketId'); ?>
            </a>
        </th>
        <th>
            <?php $urlDirection = ($this->direction == "ASC") ? "DESC" : "ASC"; ?>
            <a class="link" href="<?php echo $this->url(array('orderBy' => Db_CiTicket::CI_ID, 'direction' => (($this->orderBy == Db_CiTicket::CI_ID) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                <?php echo $this->translate('ciId'); ?>
            </a>
        </th>
        <th>
            <a class="link" href="<?php echo $this->url(array('orderBy' => Db_CiTicket::TICKET_NAME, 'direction' => (($this->orderBy == Db_CiTicket::TICKET_NAME) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                <?php echo $this->translate('ticketName'); ?>
            </a>
        </th>
        <th>
            <a class="link" href="<?php echo $this->url(array('orderBy' => Db_CiTicket::VALID_FROM, 'direction' => (($this->orderBy == Db_CiTicket::VALID_FROM) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                <?php echo $this->translate('validFrom'); ?>
            </a>
        </th>
        <th>
            <a class="link" href="<?php echo $this->url(array('orderBy' => Db_CiTicket::VALID_TO, 'direction' => (($this->orderBy == Db_CiTicket::VALID_TO) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                <?php echo $this->translate('validTo'); ?>
            </a>
        </th>
        <th>&nbsp;</th>
    </tr>

    <?php
    $row_count = 0;
    foreach ($this->paginator as $item):
        ?>
        <tr>
            <td>
                <a href="<?php echo $this->ticketurl . '/' . $item[Db_CiTicket::TICKET_ID]; ?>"><?php echo $item[Db_CiTicket::TICKET_ID]; ?></a>
            </td>
            <td>
                <a href="<?php echo APPLICATION_URL ?>ci/detail/ciid/<?php echo $item[Db_CiTicket::CI_ID]; ?>"><?php echo $item[Db_CiTicket::CI_ID]; ?></a>
            </td>
            <td><?php echo $item[Db_CiTicket::TICKET_NAME]; ?></td>
            <td><?php echo $item[Db_CiTicket::VALID_FROM]; ?></td>
            <td><?php if ($item[Db_CiTicket::VALID_TO]) {
                    echo $item[Db_CiTicket::VALID_TO];
                } else {
                    echo $this->translate('validToUnlimited');
                }; ?></td>
            <td width="50px">
                <a class="delete_list" href='#' onClick="javascript:delete_theme('<?php echo $item[Db_CiTicket::ID] ?>');" title="<?php echo $this->translate('ticketDelete') ?>" />
            </td>
        </tr>
    <?php endforeach; ?>
    <?php endif; ?>

</table>
<?php echo $this->paginator; ?>
