<script type="text/javascript">
    function deactivate_menu(menu_id) {
        if (confirm('<?php echo $this->translate('areYouSureDeactivate') ?>')) {
            window.location.href = '<?php echo APPLICATION_URL ?>menu/deactivate/menuId/' + menu_id;
        }
    }

    function activate_menu(menu_id) {
        if (confirm('<?php echo $this->translate('areYouSureActivate') ?>')) {
            window.location.href = '<?php echo APPLICATION_URL ?>menu/activate/menuId/' + menu_id;
        }
    }
</script>

<?php
$config = Zend_Registry::get('viewConfig');

$class = "link";
if ($config->ci->detail->buttons->button) {
    $class .= " button";
}

?>
<div class="button_row">
    <a class="<?php echo $class ?>" href='<?php echo APPLICATION_URL ?>menu/edit/menuId/<?php echo $this->menu[Db_Menu::ID] ?>'><?php echo $this->translate('edit'); ?></a>
    <?php if ($this->menu[Db_Menu::IS_ACTIVE]): ?>
        <a class="<?php echo $class ?> cancel" href="javascript:deactivate_menu(<?php echo $this->menu[Db_Menu::ID] ?>)"><?php echo $this->translate('delete'); ?></a>
    <?php else: ?>
        <a class="<?php echo $class ?> activate" href="javascript:activate_menu(<?php echo $this->menu[Db_Menu::ID] ?>)"><?php echo $this->translate('activate'); ?></a>
    <?php endif; ?>
    <a class="<?php echo $class ?>" href="<?php echo APPLICATION_URL ?>menu/index"><?php echo $this->translate('overview'); ?></a>
</div>

<h1 class="pageName"><?php echo $this->translate('detailMenu'); ?></h1>

<fieldset class="lordVader">
    <table>
        <tr>
            <td><strong><?php echo $this->translate('menuId'); ?></strong></td>
            <td><?php echo $this->menu[Db_Menu::ID] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('name'); ?></strong></td>
            <td><?php echo $this->menu[Db_Menu::NAME] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('description'); ?></strong></td>
            <td><?php echo $this->menu[Db_Menu::DESCRIPTION] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('note'); ?></strong></td>
            <td><?php echo $this->menu[Db_Menu::NOTE] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('order'); ?></strong></td>
            <td><?php echo $this->menu[Db_Menu::ORDER_NUMBER] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('function'); ?></strong></td>
            <td><?php echo $this->menu[Db_Menu::FUNCTION_] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('active'); ?></strong></td>
            <td>
                <input type="checkbox" disabled="disabled" <?php if ($this->menu[Db_Menu::IS_ACTIVE]) echo 'checked="checked"'; ?> />
            </td>
        </tr>
    </table>
</fieldset>
