<script type="text/javascript">
    function cancel() {
        window.location.href = "<?php echo $this->cancelUrl; ?>";
    }

    function submitForm() {
        document.forms['changePassword'].submit();
    }

    $(document).ready(function () {
        $("#tabs").tabs();
    });

</script>


<h1 class="pageName"><?php echo $this->translate('userEdit') ?></h1>
<div id="tabs">
    <ul>
        <li>
            <a href="#fragment-1"><span class="att_nr">1</span><span class="att_desc"><?php echo $this->translate('changePassword') ?></span></a>
        </li>
    </ul>
    <fieldset class="create_form steps">
        <!-- # Fragment 1 - Change password !-->
        <div id="fragment-1">
            <fieldset class="formContainer">
                <form id="changePassword" enctype="<?php echo $this->form->getEnctype() ?>" method="<?php echo $this->form->getMethod() ?>">
                    <table>
                        <tbody>
                        <tr>
                            <td><?php echo $this->translate('username'); ?></td>
                            <td><?php echo $this->userDb['name'] ?></td>
                            <td width="50%"></td>
                        </tr>
                        <tr>
                            <td><?php echo $this->translate('firstname'); ?></td>
                            <td><?php echo $this->userDb['firstname'] ?></td>
                            <td width="50%"></td>
                        </tr>
                        <tr>
                            <td><?php echo $this->translate('lastname'); ?></td>
                            <td><?php echo $this->userDb['lastname'] ?></td>
                            <td width="50%"></td>
                        </tr>
                        <?php
                        echo $this->form->password;
                        echo $this->form->password_confirm;
                        echo $this->form->password_expire_off;
                        ?>
                        </tbody>
                    </table>
                    <br><br>
                    <div class="buttonCon">
                        <input type="submit" class="standard_button" value="<?php echo $this->translate('save') ?>" onClick="javascript:submitForm(); return false;">
                        <button type="reset" class="cancel_button" onClick="cancel(); return false;"><?php echo $this->translate('abort') ?></button>
                    </div>
                </form>
            </fieldset>
        </div>
        <!-- #END Fragment 1 - Change password !-->
    </fieldset>
</div>
