<script type="text/javascript">
    function delete_user(user_id) {
        if (confirm('<?php echo $this->translate("areYouSureDelete"); ?>')) {
            window.location.href = '<?php echo APPLICATION_URL ?>user/delete/userId/' + user_id;
        }
    }

    function activate_user(user_id) {
        if (confirm('<?php echo $this->translate("areYouSureActivate"); ?>')) {
            window.location.href = '<?php echo APPLICATION_URL ?>user/activate/userId/' + user_id;
        }
    }
</script>

<div class="button_row">
    <a class="link button" href='<?php echo APPLICATION_URL ?>user/edit/userId/<?php echo $this->user[Db_User::ID] ?>'><?php echo $this->translate('edit'); ?></a>
    <?php if ($this->user[Db_User::IS_ACTIVE]): ?>
        <a class="link button cancel" href="javascript:delete_user(<?php echo $this->user[Db_User::ID] ?>)"><?php echo $this->translate('delete'); ?></a>
    <?php else: ?>
        <a class="link button activate" href="javascript:activate_user(<?php echo $this->user[Db_User::ID] ?>)"><?php echo $this->translate('activate'); ?></a>
    <?php endif; ?>
    <a class="link button" href="<?php echo APPLICATION_URL ?>user/index"><?php echo $this->translate('overview'); ?></a>
</div>

<h1 class="pageName"><?php echo $this->translate('userDetail'); ?></h1>

<fieldset class="lordVader">
    <table>
        <tr>
            <td><strong><?php echo $this->translate('userId'); ?></strong></td>
            <td><?php echo $this->user[Db_User::ID] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('username'); ?></strong></td>
            <td><?php echo $this->user[Db_User::USERNAME] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('firstname'); ?></strong></td>
            <td><?php echo $this->user[Db_User::FIRSTNAME] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('lastname'); ?></strong></td>
            <td><?php echo $this->user[Db_User::LASTNAME] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('email'); ?></strong></td>
            <td><?php echo $this->user[Db_User::EMAIL] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('description'); ?></strong></td>
            <td><?php echo $this->user[Db_User::DESCRIPTION] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('note'); ?></strong></td>
            <td><?php echo $this->user[Db_User::NOTE] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('language'); ?></strong></td>
            <td><?php echo $this->user[Db_User::LANGUAGE] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('layout'); ?></strong></td>
            <td><?php echo $this->user[Db_User::LAYOUT] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('active'); ?></strong></td>
            <td>
                <input type="checkbox" disabled="disabled" <?php if ($this->user[Db_User::IS_ACTIVE]) echo 'checked="checked"'; ?> />
            </td>
        </tr>
    </table>
    <?php if ($this->projects && count($this->projects) > 0) : ?>
        <fieldset class="detail_fieldset">
            <legend><strong><?php echo $this->translate('projects'); ?></strong></legend>
            <ul>
                <?php foreach ($this->projects as $project): ?>
                    <li><?php echo($project[Db_Project::NAME]); ?></li>
                <?php endforeach; ?>
            </ul>
        </fieldset>
    <?php endif; ?>
    <?php if ($this->roles && count($this->roles) > 0) : ?>
        <fieldset class="detail_fieldset">
            <legend><strong><?php echo $this->translate('roles'); ?></strong></legend>
            <ul>
                <?php foreach ($this->roles as $role): ?>
                    <li><?php echo($role[Db_Role::NAME]); ?></li>
                <?php endforeach; ?>
            </ul>
        </fieldset>
    <?php endif; ?>
</fieldset>
