<?php if ($this->tfaData['is_two_factor_auth'] == 0) : ?>
    <script type="text/javascript" src="<?php echo APPLICATION_URL . '/js/qrcode/qrcode.min.js'; ?>"></script>
    <script type="text/javascript">
        $(document).ready(function () {


            var qrCodeEl = document.getElementById('QRCode');

            if (typeof qrCodeEl !== null) {
                new QRCode(qrCodeEl, '<?php echo $this->tfaData['QRText'] ?>');
                $(qrCodeEl).children('img').prop('title', '');
            }

            var tfaForm = $('form.tfaVerify');

            tfaForm.bind('submit', function (evt) {
                var codeInput = $('#tfaCode');
                if (codeInput.value !== '' && codeInput.value !== ' ') {
                    var URL = '<?php echo APPLICATION_URL; ?>' + '/user/enable-tfa';
                    var data = $(this).serialize();

                    var successMessage = $('p.serverMessage .success');
                    var errorMessage = $('p.serverMessage .error');
                    var wait = $('p.serverMessage .wait');
                    var tfaSetup = $('.tfaSetup');

                    codeInput.val('');
                    successMessage.hide();
                    errorMessage.hide();
                    wait.show();

                    $.post(URL, data, function (data) {
                        wait.hide();
                        if (data.success == true) {
                            successMessage.show();
                            $(tfaSetup).empty();
                        } else {
                            errorMessage.text(data.error).show();
                        }
                    });
                }
                evt.preventDefault();
            });
        });
    </script>
<?php endif; ?>

<script type="text/javascript">
    function changePassword() {
        window.location.href = "<?php echo APPLICATION_URL . '/user/change-password/userId/' . $this->userId; ?>";
    }

    function cancel() {
        window.location.href = '<?php echo APPLICATION_URL . 'index/index'; ?>';
    }

    function submitForm() {
        document.forms['userSettings'].submit();
    }

    $(document).ready(function () {
        $("#tabs").tabs();
    });

</script>


<h1 class="pageName"><?php echo $this->translate('userEdit') ?></h1>
<?php $step = 1; ?>
<div id="tabs">
    <ul>
        <li>
            <a href="#fragment-1"><span class="att_nr">1</span><span class="att_desc"><?php echo $this->translate('general') ?></span></a>
        </li>
        <li>
            <a href="#fragment-2"><span class="att_nr">2</span><span class="att_desc"><?php echo $this->translate('2FA') ?></span></a>
        </li>
    </ul>
    <fieldset class="create_form steps">
        <!-- # Fragment 1 - General User Info !-->
        <div id="fragment-1">
            <fieldset class="formContainer">
                <form id="userSettings" enctype="<?php echo $this->form->getEnctype() ?>" method="<?php echo $this->form->getMethod() ?>">
                    <table>
                        <tbody>
                        <?php
                        echo $this->form->email;
                        echo $this->form->firstname;
                        echo $this->form->lastname;
                        echo $this->form->language;
                        ?>
                        <?php if ($this->userDb['ldapAuth']) : ?>
                            <tr class="passwordChangeDeactivatedNotice">
                                <td colspan="3">
                                    <img src="<?php echo APPLICATION_URL ?>images/icon/info_add.gif" alt="info" align="absmiddle">
                                    <span><?php echo $this->translate('passwordChangeDeactivatedNotice') ?></span>
                                </td>
                            </tr>
                        <?php endif; ?>
                        </tbody>
                    </table>
                    <br />
                    <a class="bold" href="<?php echo APPLICATION_URL ?>/login/logout/allDevices/1"><?php echo $this->translate("logoutFromAllDevices") ?></a>
                    <br><br>
                    <div class="buttonCon">
                        <input type="submit" class="standard_button" value="<?php echo $this->translate('save') ?>" onClick="javascript:submitForm(); return false;">
                        <?php if (!$this->userDb['ldapAuth']) : ?>
                        <input type="submit" class="standard_button" value="<?php echo $this->translate('changePassword') ?>" onClick="javascript:changePassword(); return false;">
                        <?php endif; ?>
                        <button type="reset" class="cancel_button" onClick="cancel(); return false;"><?php echo $this->translate('abort') ?></button>
                    </div>
                </form>
            </fieldset>
        </div>
        <!-- #END Fragment 1 - General User Info !-->

        <!-- # Fragment 2 - Two Factor Auth !-->
        <div id="fragment-2">
            <fieldset class="formContainer">
                <table>
                    <tbody>
                    <tr>
                        <td colspan="3">
                            <?php if ($this->tfaData['is_two_factor_auth'] == 0) : ?>
                                <span class="tfaSetup"><h2><?php echo $this->translate("2FASetup"); ?></h2>
                            <ol>
                                <li><a href="https://support.google.com/accounts/answer/1066447?hl=en" title="Google Authenticator" target="_blank">
                                        <?php echo $this->translate("2FAGoogleAuthInstall"); ?>
                                    </a>
                                </li>
                                <li><?php echo $this->translate("2FAGoogleAuthOpen"); ?></li>
                                <li><?php echo $this->translate("2FAGoogleAuthSetupAccount"); ?>
                                    <ol>
                                        <li id="QRCode"></li>
                                        <li><i><?php echo $this->translate("2FASecret"); ?>
                                                : </i><b><?php echo $this->tfaData['secret']; ?></b></li>
                                    </ol>

                                </li>
                                <li><?php echo $this->translate("2FAFinishSetup"); ?>
                                    <p>
                                        <form class="tfaVerify" method="post">
                                            <input type="text" name="TFAVerifyCode" placeholder="Code" id="tfaCode"><br>
                                            <input type="submit" name="verifyCode" value="<?php echo $this->translate('2FAVerifyCode'); ?>">
                                        </form>
                                    </p>
                                </li>

                            </ol></span>

                                <p class="serverMessage">
                                    <b class="wait" style="display: none;"><?php echo $this->translate('wait'); ?></b>
                                    <span class="error" style="display: none; font-size: 1.3em; color: red; font-weight: bold"></span>
                                    <span class="success" style="display: none; font-size: 1.3em; color: green; font-weight: bold"><?php echo $this->translate("2FAactive"); ?></span>
                                </p>
                            <?php else: ?>
                                <p><b><?php echo $this->translate("2FAactive"); ?></b></p>
                            <?php endif; ?>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </fieldset>
        </div>
        <!-- #END Fragment 2 - Two Factor Auth !-->
    </fieldset>
</div>
