Hallo <?php echo $this->data['cmdb'] ?>-Admin,<br>
<br>
du bekommst diese Mail, weil das Passwort des Benutzers <?php echo $this->data['username']; ?> bald abläuft und er keine Mailadresse hinterlegt hat.
<br>
<br>
Um dies zu ändern, logge dich unter <?php echo $this->data['host']; ?> ein und bearbeite diesen Benutzer.<br>
<br>
Mit freundlichen Gr&uuml;&szlig;en<br>
<?php echo $this->data['cmdb'] ?><br>