Hallo <?php echo $this->data['cmdb'] ?>-Nutzer,<br>
<br>
du bekommst diese Email, weil dein Passwort f&uuml;r deinen Benutzer bei <?php echo $this->data['cmdb']; ?> in <?php echo $this->data['daysleft']; ?> Tagen abl&auml;uft.
<br>
<br>
Bitte &auml;ndere dein Passwort bevor es abgelaufen ist &uuml;ber die Benutzereinstellungen (wenn du momentan eingeloggt bist
<a href="<?php echo $this->data['link']; ?>">klick hier</a>)<br>
<br>
Mit freundlichen Gr&uuml;&szlig;en<br>
<?php echo $this->data['cmdb'] ?><br>