<script language="JavaScript" type="text/javascript" src="<?php echo APPLICATION_URL; ?>js/tooltip/wz_tooltip.js"></script>
<script language="JavaScript" type="text/javascript" src="<?php echo APPLICATION_URL; ?>js/flexBox.js"></script>
<script type="text/javascript">

    function submit() {
        document.forms['create'].submit();
    }

    function next() {
        var selected = $("#tabs").tabs("option", "active");
        var next = getNextEnabledTab(selected);
        $("#tabs").tabs({active: next});
    }

    function back() {
        var selected = $("#tabs").tabs("option", "active");
        var last = getLastEnabledTab(selected);
        $("#tabs").tabs({active: last});
    }

    function getNextEnabledTab(index) {
        index += 1;
        var disabled = $("#tabs").tabs("option", "disabled");
        for (var i = 0; i < disabled.length; i++) {
            if (disabled[i] == index)
                index = getNextEnabledTab(index);
        }

        return index;
    }

    function getLastEnabledTab(index) {
        index -= 1;
        var disabled = $("#tabs").tabs("option", "disabled");
        for (var i = 0; i < disabled.length; i++) {
            if (disabled[i] == index)
                index = getLastEnabledTab(index);
        }

        return index;
    }

    $(window).resize(function () {
        insertDynamicHeader('userTab');
        insertDynamicHeader('rightsTab');
    });

    $(document).ready(function () {

        insertDynamicHeader('userTab');
        insertDynamicHeader('rightsTab');

        $(document).keypress(function (e) {
            if (e.which == 13) {
                if ($(e.target).attr('id') == 'searchStringUser') {
                    searchUserFunction();
                } else if ($(e.target).attr('id') == 'searchStringAttributes') {
                    searchAttributesFunction();
                }
                e.preventDefault();
                return false;
            }
        });

        $("#tabs").tabs({active: 0});

        $(".cancel_button").bind('click', function (evt) {
            evt.preventDefault();
            window.location.href = '<?php echo APPLICATION_URL . 'role/index'; ?>';
        });
    })
</script>

<div class="button_row">
    <a href="<?php echo APPLICATION_URL ?>role/index"><?php echo $this->translate('overview') ?></a>

</div>
<h1 class="pageName"><?php echo $this->translate('roleEdit') ?></h1>

<div id="tabs">
    <ul>
        <li>
            <a href="#fragment-1"><span class="att_nr">1</span><span class="att_desc"><?php echo $this->translate('roleEdit') ?></span></a>
        </li>
        <li>
            <a href="#fragment-2"><span class="att_nr">2</span><span class="att_desc"><?php echo $this->translate('user') ?></span></a>
        </li>
        <li>
            <a href="#fragment-3"><span class="att_nr">2</span><span class="att_desc"><?php echo $this->translate('permissions') ?></span></a>
        </li>
    </ul>
    <fieldset class="create_form steps">
        <form widgetid="create" id="create" enctype="multipart/form-data" method="post" dojoattachpoint="containerNode" dojoattachevent="onreset:_onReset,onsubmit:_onSubmit">

            <div id="fragment-1">
                <fieldset class="formContainer">
                    <table>
                        <?php echo $this->form->name ?>
                        <?php echo $this->form->description ?>
                        <?php echo $this->form->note ?>
                    </table>
                </fieldset>
                <div class="buttonCon">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('save') ?>" onClick="javacript:submit()">
                    <input type="button" class="cancel_button" value="<?php echo $this->translate('cancel') ?>">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('next') ?>" onClick="javacript:next();return false;">
                </div>
            </div>

            <div id="fragment-2">
                <fieldset class="formContainer">
                    <div id="userFilter">
                        <?php echo $this->partial('templates/_user_filter.phtml',
                            array('dropdown_options_user' => $this->filterOptionsUser,
                                  'default_option_user'   => $this->defaultOptionUser)) ?>
                    </div>

                    <!-- dynamic header section -->
                    <table>
                        <div id="userHeaderRow">
                            <div id="dynamicUserHeader">
                                <a class="all user" href="#"><span title="<?php echo $this->translate('roleUserCheckDescription') ?>">x</span></a>
                                <span title="<?php echo $this->translate('userName') ?>"><?php echo $this->translate('user') ?></span>
                            </div>
                        </div>
                    </table><!-- end of dynamic header section -->

                    <div class="flexBox">
                        <div class="parent parentUsers">
                            <?php foreach ($this->users as $user): ?>
                                <?php $formfield = 'userId_' . $user[Db_User::ID]; ?>
                                <div class="child">
                                    <div style="display:inline-block">
                                        <label>
                                            <?php echo $this->form->$formfield ?>
                                        </label>
                                    </div>
                                    <span class="userTitle" title="<?php echo $user[Db_User::NOTE] ?>"><?php echo $user[Db_User::USERNAME] ?></span>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </fieldset>
                <div class="buttonCon">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('save') ?>" onClick="javacript:submit()">
                    <input type="button" class="cancel_button" value="<?php echo $this->translate('cancel') ?>">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('back') ?>" onClick="javascript:back();return false;">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('next') ?>" onClick="javacript:next();return false;">
                </div>
            </div>
            <div id="fragment-3">
                <fieldset class="formContainer">
                    <div id="permissionFilter">
                        <?php echo $this->partial('templates/_permission_filter.phtml',
                            array('dropdown_options_permission' => $this->filterOptionsPermission,
                                  'default_option_permission'   => $this->defaultOptionPermission)) ?>
                    </div>

                    <!-- dynamic header section -->
                    <table>
                        <div id="xmoHeaderRow">
                            <div id="dynamicXmOciTypeHeader">
                                <div class="radio_group">
                                    <div class="radio_label">
                                        <a class="all first" href="#"><span title="<?php echo $this->translate("off"); ?>">x</span></a>
                                    </div>
                                    <div class="radio_label">
                                        <a class="all second" href="#"><span title="<?php echo $this->translate("read"); ?>">r</span></a>
                                    </div>
                                    <div class="radio_label">
                                        <a class="all third" href="#"><span title="<?php echo $this->translate("read_write"); ?>">r/w</span></a>
                                    </div>
                                </div>
                                <span title="<?php echo $this->translate("roles"); ?>"><?php echo $this->translate("attr"); ?></span>
                            </div>
                        </div>
                    </table><!-- end of dynamic header section -->

                    <div class="flexBox">
                        <div class="parent parentPermissions">
                            <?php foreach ($this->attributes as $attribute): ?>
                                <?php $formfield = 'attributeId_' . $attribute[Db_Attribute::ID]; ?>
                                <div class="child">
                                    <?php echo $this->form->$formfield ?>
                                    <span class="attributeTitle" style="width:76%" id="<?php echo $attribute[Db_Attribute::DESCRIPTION] ?>" ;title="<?php echo $attribute[Db_Attribute::DESCRIPTION] ?>"><?php echo $attribute[Db_Attribute::NAME] ?></span>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </fieldset>
                <div class="buttonCon">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('save') ?>" onClick="javacript:submit()">
                    <input type="button" class="cancel_button" value="<?php echo $this->translate('cancel') ?>">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('back') ?>" onClick="javascript:back();return false;">
                </div>
            </div>

        </form>
    </fieldset>

</div>
