<script type="text/javascript">
    function reset() {

        window.location.href = '<?php echo APPLICATION_URL . 'theme/index'; ?>';

    }

    function submit() {
        document.forms['create'].submit();
    }

    function next() {
        var selected = $("#tabs").tabs("option", "active");
        var next = getNextEnabledTab(selected);
        $("#tabs").tabs({active: 1});
    }

    function back() {
        var selected = $("#tabs").tabs("option", "active");
        var last = getLastEnabledTab(selected);
        $("#tabs").tabs({active: 0});
    }

    $(document).ready(function () {
        $(document).ready(function () {
            $("form#create input").keypress(function (e) {
                if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
                    submit();
                }
            });
            $("form#create select").keypress(function (e) {
                if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
                    submit();
                }
            });
        });

        $("#tabs").tabs({active: 0});
    })


</script>
<div class="button_row">
    <a href="<?php echo APPLICATION_URL ?>theme/index"><?php echo $this->translate('overview') ?></a>
</div>
<h1 class="pageName"><?php echo $this->translate('themeCreate') ?></h1>
<div id="tabs">
    <ul>
        <li>
            <a href="#fragment-1"><span class="att_nr">1</span><span class="att_desc"><?php echo $this->translate('createTheme') ?></span></a>
        </li>
        <li>
            <a href="#fragment-2"><span class="att_nr">2</span><span class="att_desc"><?php echo $this->translate('modules') ?></span></a>
        </li>
    </ul>
    <fieldset class="create_form steps">
        <form name="<?php echo $this->escape($this->form->getName()) ?>" action="<?php echo $this->escape($this->form->getAction()) ?>"
              method="<?php echo $this->escape($this->form->getMethod()) ?>">
            <div id="fragment-1">
                <fieldset class="formContainer">
                    <table style="margin-bottom: 15px;">
                        <?php
                        echo $this->form->name;
                        echo $this->form->description;
                        echo $this->form->note;
                        echo $this->form->searchlist;
                        echo $this->form->startpage;
                        echo $this->form->wildcard;
                        echo $this->form->valid;
                        echo $this->form->themeid;

                        $count = 0;
                        $rows  = 0;
                        $ipr   = ceil((count($this->menuList)) / 3);

                        $firstList  = array();
                        $secondList = array();
                        $thirdList  = array();

                        foreach ($this->menuList as $menu) {

                            if ($rows < $ipr) {
                                $firstList[$count] = $menu[Db_Menu::ID];
                                $rows++;
                                $count++;
                            } else if ($rows < ($ipr * 2)) {
                                if (count($secondList) == 0) {
                                    $count = 0;
                                }
                                $secondList[$count] = $menu[Db_Menu::ID];
                                $rows++;
                                $count++;
                            } else {
                                if (count($thirdList) == 0) {
                                    $count = 0;
                                }
                                $thirdList[$count] = $menu[Db_Menu::ID];
                                $rows++;
                                $count++;
                            }
                        }
                        ?>
                    </table>
                </fieldset>
            </div>
            <div id="fragment-2">
                <fieldset class="formContainer">
                    <table>
                        <tr>
                            <th style="width:33%">
                                <div style="float:left; width:25px; text-align:center;">
                                    <a class="all check" href="#">x</a></div>
                                <span><?php echo $this->translate('module'); ?></span>
                            </th>
                            <th style="width:33%">
                                <div style="float:left; width:25px; text-align:center;">
                                    <a class="all check" href="#">x</a></div>
                                <span><?php echo $this->translate('module'); ?></span>
                            </th>
                            <th style="width:33%">
                                <div style="float:left; width:25px; text-align:center;">
                                    <a class="all check" href="#">x</a></div>
                                <span><?php echo $this->translate('module'); ?></span>
                            </th>
                        </tr>
                        <?php for ($i = 0; $i < $ipr; $i++) { ?>
                            <tr>
                                <td>
                                    <div style="float:left; width:25px; text-align:center;"><?php if ($this->form->{$firstList[$i]}) echo $this->form->{$firstList[$i]}->setDecorators(array('ViewHelper')) ?></div>
                                    <span><?php if ($this->form->{$firstList[$i]}) echo $this->form->{$firstList[$i]}->getLabel() ?></span>
                                </td>
                                <td>
                                    <div style="float:left; width:25px; text-align:center;"><?php if ($this->form->{$secondList[$i]}) echo $this->form->{$secondList[$i]}->setDecorators(array('ViewHelper')) ?></div>
                                    <span><?php if ($this->form->{$secondList[$i]}) echo $this->form->{$secondList[$i]}->getLabel() ?></span>
                                </td>
                                <td>
                                    <div style="float:left; width:25px; text-align:center;"><?php if ($this->form->{$thirdList[$i]}) echo $this->form->{$thirdList[$i]}->setDecorators(array('ViewHelper')) ?></div>
                                    <span><?php if ($this->form->{$thirdList[$i]}) echo $this->form->{$thirdList[$i]}->getLabel() ?></span>
                                </td>
                            </tr>
                        <?php } ?>


                    </table>
                </fieldset>
            </div>
        </form>
        <div class="buttonCon">
            <input type="submit" class="standard_button" value="<?php echo $this->translate('save') ?>" onClick="javacript:submit()">
            <input type="submit" class="cancel_button" value="<?php echo $this->translate('cancel') ?>" onClick="javascript:reset(); return false;">
        </div>
    </fieldset>
</div>	
	
		
			
