<script language="JavaScript" type="text/javascript" src="<?php echo APPLICATION_URL; ?>js/filter.js"></script>
<script type="text/javascript">
    function delete_theme(id) {
        if (confirm('<?php echo $this->translate('themeDeleteCheck') ?>')) {
            window.location.href = '<?php echo APPLICATION_URL?>theme/delete/themeId/' + id + '/';
        }
    }

    function activate_theme(id) {
        if (confirm('<?php echo $this->translate('themeActivateCheck') ?>')) {
            window.location.href = '<?php echo APPLICATION_URL?>theme/activate/themeId/' + id + '/';
        }
    }
</script>

<?php
$config = Zend_Registry::get('viewConfig');

$class = "link";
if ($config->ci->detail->buttons->button) {
    $class = " button";
}
?>
<div class="button_row">
    <a class="<?php echo $class; ?> create" href="<?php echo APPLICATION_URL ?>theme/create"><?php echo $this->translate('themeCreate') ?></a>
</div>

<h1 class="pageName"><?php echo $this->translate('themes') ?></h1>
<div class="numberResult">
    (<?php echo $this->translate('numberOfResults') ?> <?php echo($this->paginator->getTotalItemCount()) ?>)
</div>

<div id="filter">
    <div class="filter-box">
        <form name="<?php echo $this->escape($this->searchForm->getName()) ?>"
              action="<?php echo $this->escape($this->searchForm->getAction()) ?>"
              method="<?php echo $this->escape($this->searchForm->getMethod()) ?>">
            <?php
            echo $this->searchForm->search->setDecorators(array('Errors', array('ViewHelper', array('tag' => '<div>'))));
            echo $this->searchForm->filterButton;
            ?>
        </form>
    </div>
</div>
<div class="clearBoth" style="margin-bottom: 15px;"></div>
<?php if (count($this->paginator)): ?>
    <table class="list" cellpadding="0" cellspacing="0" width="100%">
        <tr class="headline">
            <th>
                <?php $urlDirection = ($this->direction == "ASC") ? "DESC" : "ASC"; ?>
                <a href="<?php echo APPLICATION_URL ?>theme/index/page/<?php echo $this->page ?>/orderBy/<?php echo Db_Theme::NAME ?>/direction/<?php echo(($this->orderBy == Db_Theme::NAME) ? $urlDirection : "DESC"); ?>">
                    <?php echo $this->translate('name'); ?>
                </a>
            </th>
            <th>
                <a href="<?php echo APPLICATION_URL ?>theme/index/page/<?php echo $this->page ?>/orderBy/<?php echo Db_Theme::DESCRIPTION ?>/direction/<?php echo(($this->orderBy == Db_Theme::DESCRIPTION) ? $urlDirection : "ASC"); ?>">
                    <?php echo $this->translate('description'); ?>
                </a>
            </th>
            <th>
                <a href="<?php echo APPLICATION_URL ?>theme/index/page/<?php echo $this->page ?>/orderBy/<?php echo Db_Theme::NOTE ?>/direction/<?php echo(($this->orderBy == Db_Theme::NOTE) ? $urlDirection : "ASC"); ?>">
                    <?php echo $this->translate('note'); ?>
                </a>
            </th>
            <th>
                <a href="<?php echo APPLICATION_URL ?>theme/index/page/<?php echo $this->page ?>/orderBy/<?php echo Db_Theme::IS_ACTIVE ?>/direction/<?php echo(($this->orderBy == Db_Theme::IS_ACTIVE) ? $urlDirection : "ASC"); ?>">
                    <?php echo $this->translate('valid'); ?>
                </a>
            </th>
            <th>&nbsp;</th>
        </tr>
        <?php
        $row_count = 0;
        foreach ($this->paginator as $item):
            ?>
            <?php
            if (!$item[Db_Theme::IS_ACTIVE]) {
                ?>
                <tr class="inactive">
                <?php
            } else {
                ?>
                <tr>
                <?php
            }
            ?>
            <td>
                <a class="link" href="<?php echo APPLICATION_URL ?>theme/edit/themeId/<?php echo $item[Db_Theme::ID]; ?>"><?php echo Bootstrap::xssCleanView($item[Db_Theme::NAME]); ?></a>
            </td>
            <td><?php echo Bootstrap::xssCleanView($item[Db_Theme::DESCRIPTION]); ?></td>
            <td><?php echo Bootstrap::xssCleanView($item[Db_Theme::NOTE]); ?></td>
            <td><?php if ($item[Db_Theme::IS_ACTIVE]) {
                    echo $this->translate('active');
                } else {
                    echo $this->translate('inactive');
                } ?></td>
            <td width="80px">
                <?php if ($item[Db_Theme::IS_ACTIVE]): ?>
                    <a class="delete_list" href="javascript:delete_theme('<?php echo $item[Db_Theme::ID] ?>');" title="<?php echo $this->translate('themeIndexLinkDelete') ?>"></a>
                <?php endif; ?>
                <div class="rfloater">
                    <a class="duplicate_list buttonLink" href="<?php echo APPLICATION_URL ?>theme/create/cloneFromId/<?php echo $item[Db_Theme::ID] ?>" title="<?php echo $this->translate('duplicate') ?>">&nbsp;</a>
                    <a class="edit_list buttonLink" href="<?php echo APPLICATION_URL ?>theme/edit/themeId/<?php echo $item[Db_Theme::ID]; ?>" title="<?php echo $this->translate('edit') ?>">&nbsp;</a>
                    <?php if (!$item[Db_Theme::IS_ACTIVE]): ?>
                        <a href="#" onclick="javascript:activate_theme(<?php echo $item[Db_Theme::ID]; ?>);"><img class="delete_list" src='<?php echo APPLICATION_URL . "images/icon/activate.png" ?>' title="<?php echo $this->translate('activate') ?>"></a>
                    <?php endif; ?>
                </div>
            </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?php echo $this->paginator; ?>
<?php else: ?>
    <div class="error_message">
        <?php echo $this->translate('noThemeFound') ?>
    </div>
<?php endif; ?>