<script type="text/javascript">


    $(document).ready(function () {
        var colorPickerOpen = 0;
        var position = null;
        var displayColorPicker = function () {
            if (colorPickerOpen == 0) {
                position = $(this).offset();
                position.left -= 80;
                position.top += 15;
                $("#filePicker-" + $(this).attr('id')).offset(position);
                $("#filePicker-" + $(this).attr('id')).fadeIn('slow', function () {
                    colorPickerOpen = 1;
                });
            }
            else
                $("#filePicker-" + $(this).attr('id')).fadeOut("slow", function () {
                    colorPickerOpen = 0;
                });
        };
        $(".filepickerHolder").hover(function () {
            position = $(this).offset();
            position.left -= 80;
            position.top += 0;
            $("#filePicker-" + $(this).attr('id')).offset(position);
            $("#filePicker-" + $(this).attr('id')).fadeIn('slow', function () {
                colorPickerOpen = 1;
            });

            $("#filePicker-" + $(this).attr('id')).mouseleave(function () {
                $(this).fadeOut("slow", function () {
                    colorPickerOpen = 0;
                });
            });
        });
    }); // document ready

</script>

<h1 class="pageName"><?php echo $this->translate('idleTitle'); ?></h1>
<div class="numberResult">
    (<?php echo $this->translate('numberOfResults') ?> <?php echo($this->paginator->getTotalItemCount()) ?>)
</div>

<?php if (count($this->paginator)): ?>
    <table class="list" cellpadding="0" cellspacing="0" width="100%">
        <tr class="headline">
            <th><?php echo $this->translate('filename'); ?></th>
            <th><?php echo $this->translate('dateProceeded'); ?></th>
            <th><?php echo $this->translate('log'); ?></th>
            <th>&nbsp;</th>
        </tr>
        <?php
        $row_count = 0;
        foreach ($this->paginator as $key => $item):
            ?>
            <tr>
                <td><a href="<?php echo $this->filePath . '/' . $item['file'] ?>"><?php echo $item['file']; ?></a></td>
                <td><?php echo $item['time'] ?></td>
                <td>
                    <a href="<?php echo $this->filePath . '/log/' . $item['file'] . '.log' ?>"><?php echo $this->translate('log'); ?></a>
                </td>

                <td>
                    <a class="delete_list" href="<?php echo APPLICATION_URL ?>fileimport/queue/type/idle/method/delete/file/<?php echo $item['file']; ?>"></a>
                    <div class="rfloater">
                        <span class="link buttonLink filepickerHolder" id="<?php echo $key; ?>">&nbsp;</span>
                        <div class="filePicker" id="filePicker-<?php echo $key; ?>">
                            <?php echo $this->translate('pickImport'); ?>
                            <ul style="padding-left:0;">
                                <li style="padding-left: 5px; list-style-type: square; list-style-position: inside;">
                                    <a href="<?php echo APPLICATION_URL ?>fileimport/queue/type/idle/method/import/folder/attribute/file/<?php echo $item['file']; ?>"><?php echo $this->translate('importAttribute'); ?></a>
                                </li>
                                <li style="padding-left: 5px; list-style-type: square; list-style-position: inside;">
                                    <a href="<?php echo APPLICATION_URL ?>fileimport/queue/type/idle/method/import/folder/insert/file/<?php echo $item['file']; ?>"><?php echo $this->translate('importInsert'); ?></a>
                                </li>
                                <li style="padding-left: 5px; list-style-type: square; list-style-position: inside;">
                                    <a href="<?php echo APPLICATION_URL ?>fileimport/queue/type/idle/method/import/folder/autoupdate/file/<?php echo $item['file']; ?>"><?php echo $this->translate('importUpdateAuto'); ?></a>
                                </li>
                                <li style="padding-left: 5px; list-style-type: square; list-style-position: inside;">
                                    <a href="<?php echo APPLICATION_URL ?>fileimport/queue/type/idle/method/import/folder/manualupdate/file/<?php echo $item['file']; ?>"><?php echo $this->translate('importUpdateManual'); ?></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>

    </table>
    <?php echo $this->paginator; ?>
<?php endif; ?>