<script language="JavaScript" type="text/javascript" src="<?php echo APPLICATION_URL . 'js/tinymce/jscripts/tiny_mce/tiny_mce.js' ?>"></script>
<script type="text/javascript">
    function finalizeFileUpdate() {
    }
</script>
<!-- TinyMCE -->
<script type="text/javascript">
    tinyMCE.init({
        // General options
        theme: "advanced",
        editor_selector: "tinymc_textarea",
        mode: "specific_textareas",
        plugins: "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",

        // Theme options
        theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect,|,forecolor,backcolor",
        theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,link,unlink,anchor,cleanup,help,code,|,insertdate,inserttime",
        theme_advanced_buttons3: "",
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left",
        theme_advanced_statusbar_location: "bottom",
        theme_advanced_resizing: true,

        // Drop lists for link/image/media/template dialogs
        template_external_list_url: "lists/template_list.js",
        external_link_list_url: "lists/link_list.js",
        external_image_list_url: "lists/image_list.js",
        media_external_list_url: "lists/media_list.js",

        // Style formats
        style_formats: [
            {title: 'Bold text', inline: 'b'},
            {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
            {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
            {title: 'Example 1', inline: 'span', classes: 'example1'},
            {title: 'Example 2', inline: 'span', classes: 'example2'},
            {title: 'Table styles'},
            {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
        ]

    });
</script>
<!-- /TinyMCE -->

<div class="button_row">
    <a class="link button" href="<?php echo APPLICATION_URL . 'fileupload/edit/file/' . $this->file; ?>/filetype/<?php echo $this->filetype; ?>/ciId/<?php echo $this->ciId ?>/editor/true"><?php echo $this->translate('editorTrue') ?></a>
    <a class="link button" href="<?php echo APPLICATION_URL . 'fileupload/edit/file/' . $this->file; ?>/filetype/<?php echo $this->filetype; ?>/ciId/<?php echo $this->ciId ?>/"><?php echo $this->translate('editorFalse') ?></a>
</div>

<body onLoad="<?php echo $this->onLoad ?>">

</body>

<div class='fileupload'>
    <?php echo $this->form ?>
</div>