<?php
$version = $this->cmdbVersion['build number'];
$request = Zend_Controller_Front::getInstance()->getRequest();
$config  = new Zend_Config_Ini(APPLICATION_PATH . '/configs/individualization.ini', APPLICATION_ENV);
?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="x-ua-compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php echo $this->headTitle(); ?>
    <link type="text/css" href="<?php echo APPLICATION_URL; ?>/css/global.css" rel="stylesheet">
    <link rel="StyleSheet" href="<?php echo APPLICATION_URL; ?>js/jquery/css/jquery-ui.min.css?v=<?php echo $version ?>" type="text/css" media="screen" />
    <link rel="StyleSheet" href="<?php echo APPLICATION_URL; ?>js/jquery/css/jquery-ui-infocmdb.min.css?v=<?php echo $version ?>" type="text/css" media="screen" />

    <?php echo $this->partial('_customization.phtml', array(
        'version'                 => $version,
        'individualizationConfig' => $config,
    )); ?>
    <script language="JavaScript" type="text/javascript" src="<?php echo APPLICATION_URL; ?>js/jquery/jquery-1.12.4.min.js?v=<?php echo $version ?>"></script>
    <script language="JavaScript" type="text/javascript" src="<?php echo APPLICATION_URL; ?>js/jquery/jquery-ui-1.11.4.min.js?v=<?php echo $version ?>"></script>
    <script language="JavaScript" type="text/javascript" src="<?php echo APPLICATION_URL; ?>js/utils/util.min.js?v=<?php echo $version ?>"></script>
</head>
<body
    <?php if ($this->onLoad) echo ' onLoad="' . $this->onLoad . '"' ?>
        class="
            layout-layout
            <?php echo $request->getControllerName(); ?>-controller
            <?php echo $request->getActionName(); ?>-action
        "
>
<?php
// fetch 'content' key using layout helper:
echo $this->layout()->content;
?>
<div id="infocmdb-modal-container" style="display:none;"></div>
</body>
</html>