<?php
$config = Zend_Registry::get('viewConfig');

$class = "link";
if ($config->ci->detail->buttons->button) {
    $class .= " button";
}

?>
    <div class="button_row">
        <a class="<?php echo $class; ?>" href="<?php echo APPLICATION_URL . 'import/create' ?>"><?php echo $this->translate('createConfig') ?></a>
    </div>
    <h1 class="pageName"><?php echo $this->translate('fileimportConfig') ?></h1>

<?php if (count($this->paginator)): ?>
    <table class="list" cellpadding="0" cellspacing="0" width="100%">
    <tr class="headline">
        <th>
            <?php $urlDirection = ($this->direction == "ASC") ? "DESC" : "ASC"; ?>
            <a href="<?php echo APPLICATION_URL ?>import/config/page/<?php echo $this->page ?>/orderBy/<?php echo Db_CiType::ID ?>/direction/<?php echo(($this->orderBy == Db_FileImport::ID) ? $urlDirection : "ASC"); ?>">
                <?php echo $this->translate('configId'); ?>
            </a>
        </th>
        <th>
            <a href="<?php echo APPLICATION_URL ?>import/config/page/<?php echo $this->page ?>/orderBy/<?php echo Db_FileImport::NAME ?>/direction/<?php echo(($this->orderBy == Db_FileImport::NAME) ? $urlDirection : "ASC"); ?>">
                <?php echo $this->translate('name'); ?>
            </a>
        </th>
        <th>
            <a href="<?php echo APPLICATION_URL ?>import/config/page/<?php echo $this->page ?>/orderBy/<?php echo Db_FileImport::DESCRIPTION ?>/direction/<?php echo(($this->orderBy == Db_FileImport::DESCRIPTION) ? $urlDirection : "ASC"); ?>">
                <?php echo $this->translate('description'); ?>
            </a>
        </th>
        <th>
            <a href="<?php echo APPLICATION_URL ?>import/config/page/<?php echo $this->page ?>/orderBy/<?php echo Db_FileImport::NOTE ?>/direction/<?php echo(($this->orderBy == Db_FileImport::NOTE) ? $urlDirection : "ASC"); ?>">
                <?php echo $this->translate('note'); ?>
            </a>
        </th>
        <th>
            <a href="<?php echo APPLICATION_URL ?>import/config/page/<?php echo $this->page ?>/orderBy/<?php echo Db_FileImport::HOST ?>/direction/<?php echo(($this->orderBy == Db_FileImport::HOST) ? $urlDirection : "ASC"); ?>">
                <?php echo $this->translate('host'); ?>
            </a>
        </th>
        <th>&nbsp;</th>
    </tr>
    <?php
    $row_count = 0;
    foreach ($this->paginator as $item):
        ?>
        <tr>
            <td>
                <a href='<?php echo APPLICATION_URL . "citype/detail/citypeId/" . $item[Db_FileImport::ID]; ?>'><?php echo $item[Db_FileImport::ID]; ?></a>
            </td>
            <td><?php echo $item[Db_FileImport::NAME]; ?></td>
            <td><?php echo $item[Db_FileImport::DESCRIPTION]; ?></td>
            <td><?php echo $item[Db_FileImport::NOTE]; ?></td>
            <td><?php echo $item[Db_FileImport::HOST]; ?></td>
            <td>
                <a class="delete_list" href='<?php echo APPLICATION_URL . "import/deleteconfig/configId/" . $item[Db_FileImport::ID]; ?>'></a>
                <div class="rfloater">
                    <a class="link  buttonLink" href='<?php echo APPLICATION_URL . "import/editconfig/configId/" . $item[Db_FileImport::ID]; ?>'><?php echo $this->translate('edit') ?></a>
                </div>
            </td>
        </tr>
    <?php
    endforeach;
else:
    ?>
    <h1 class="pageName"><?php echo $this->translate('noConfigFound'); ?></h1>
<?php endif; ?>

    </table>
<?php echo $this->paginator; ?>