<script type="text/javascript">
    function cancel_form() {
        window.location.href = '<?php echo APPLICATION_URL . 'announcement/index'; ?>';
    }
</script>
<div class="button_row">
    <a href="<?php echo APPLICATION_URL ?>announcement/index"><?php echo $this->translate('overview') ?></a>
</div>
<h1 class="pageName"><?php echo $this->translate('announcementCreate') ?></h1>
<form name="<?php echo $this->escape($this->form->getName()) ?>"
      action="<?php echo $this->escape($this->form->getAction()) ?>"
      method="<?php echo $this->escape($this->form->getMethod()) ?>">
    <fieldset class="lordVader">
        <table style="margin-bottom: 15px;" class="form_simple">
            <?php
            echo $this->form->name;
            echo $this->form->type;
            echo $this->form->title_de;
            echo $this->form->message_de;
            echo $this->form->title_en;
            echo $this->form->message_en;
            echo $this->form->show_from_date;
            echo $this->form->show_to_date;
            echo $this->form->valid;
            ?>
        </table>
        <div class="buttonCon">
            <input type="submit" class="standard_button" value="<?php echo $this->translate('save') ?>">
            <input type="button" class="cancel_button" value="<?php echo $this->translate('cancel') ?>" onClick="cancel_form()">
        </div>
    </fieldset>
</form>		
