<?php
$config = Zend_Registry::get('viewConfig');

$class = "link";
if ($config->ci->detail->buttons->button) {
    $class .= " button";
}

?>
<div class="button_row">
    <a class="<?php echo $class; ?>" href="<?php echo APPLICATION_URL ?>log/index/type/<?php echo $this->linkType ?>"><?php echo $this->translate($this->linkType) ?></a>
</div>

<h1 class="pageName"><?php echo $this->translate('logs') ?></h1>
<ul>
    <?php
    if ($this->importImportLogs && count($this->importImportLogs) > 0) {
        foreach ($this->importImportLogs as $key => $logs) {
            ?>
            <li><span><strong><?php echo $key; ?></strong></span></li>
            <ul>
                <?php foreach ($logs as $file): ?>
                    <li>
                        <a href="<?php echo APPLICATION_URL ?>log/detail/type/<?php echo $this->type ?>/file/<?php echo $key . '>>' . $file['title'] ?>"><?php echo $file['title'] ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
            <?php
        }
    }
    if ($this->mainLogs && count($this->mainLogs) > 0) {
        foreach ($this->mainLogs as $key => $file) {
            ?>
            <li>
                <a href="<?php echo APPLICATION_URL ?>log/detail/type/<?php echo $this->type ?>/file/<?php echo $file['title'] ?>"><?php echo $file['title'] ?></a>
            </li>
            <?php
        }
    }
    ?>
</ul>
