<script language="JavaScript" type="text/javascript"
        src="<?php echo APPLICATION_URL; ?>js/filter.js"></script>
<script type="text/javascript">
    function updatePage(page) {
        <?php
        $url = $this->url(array(
            'orderBy'   => $this->orderBy,
            'direction' => $this->direction,
            'filter'    => $this->filter,
            'page'      => null,
        ));
        if (!strstr($url, 'index'))
            $url .= '/index';
        ?>
        var filterDefault = 'Filter';
        if ($("#search").val() == filterDefault)
            $("#search").val('');
        document.forms['searchForm'].action = "<?php echo $url; ?>/page/" + page;
        document.forms['searchForm'].submit();
        return false;
    }

    function delete_attribute(attribute_id) {
        if (confirm('<?php echo $this->translate('areYouSureDelete') ?>')) {
            window.location.href = '<?php echo APPLICATION_URL ?>attribute/delete/attributeId/' + attribute_id;
        }
    }

    function activate_attribute(attribute_id) {
        if (confirm('<?php echo $this->translate('areYouSureActivate') ?>')) {
            window.location.href = '<?php echo APPLICATION_URL ?>attribute/activate/attributeId/' + attribute_id;
        }
    }

</script>

<?php
$config = Zend_Registry::get('viewConfig');

$class = "link";
if ($config->ci->detail->buttons->button) {
    $class .= " button";
}

?>
<div class="button_row">
    <a class="<?php echo $class; ?> create"
       href="<?php echo APPLICATION_URL ?>attribute/create"><?php echo $this->translate('createAttribute') ?></a>
</div>
<h1 class="pageName"><?php echo $this->translate('attributes') ?></h1>
<div class="numberResult">
    (<?php echo $this->translate('numberOfResults') ?> <?php echo($this->paginator->getTotalItemCount()) ?>)
</div>
<div id="filter">
    <div class="filter-box">
        <form name="<?php echo $this->escape($this->searchForm->getName()) ?>"
              action="<?php echo $this->escape($this->searchForm->getAction()) ?>"
              method="<?php echo $this->escape($this->searchForm->getMethod()) ?>">
            <?php
            echo $this->searchForm->search->setDecorators(array(
                'Errors',
                array(
                    'ViewHelper',
                    array(
                        'tag' => '<div>',
                    ),
                ),
            ));
            echo $this->searchForm->filterButton;
            ?>
        </form>
    </div>
</div>

<div class="break"></div>

<?php if (count($this->paginator)): ?>
    <table class="list" cellpadding="0" cellspacing="0" width="100%">
        <tr class="headline">
            <?php $urlDirection = ($this->direction == "ASC") ? "DESC" : "ASC"; ?>
            <th><a
                        href="<?php echo $this->url(array('page' => $this->page, 'orderBy' => Db_Attribute::NAME, 'direction' => (($this->orderBy == Db_Attribute::NAME) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('name') ?>
                </a></th>
            <th><a
                        href="<?php echo $this->url(array('page' => $this->page, 'orderBy' => Db_Attribute::DESCRIPTION, 'direction' => (($this->orderBy == Db_Attribute::DESCRIPTION) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('description') ?>
                </a></th>
            <th><a
                        href="<?php echo $this->url(array('page' => $this->page, 'orderBy' => Db_Attribute::ATTRIBUTE_GROUP_ID, 'direction' => (($this->orderBy == Db_Attribute::ATTRIBUTE_GROUP_ID) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('displayType') ?>
                </a></th>
            <th><a
                        href="<?php echo $this->url(array('page' => $this->page, 'orderBy' => 'attributeTypeName', 'direction' => (($this->orderBy == 'attributeTypeName') ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('attributeType') ?>
                </a></th>
            <th><a
                        href="<?php echo $this->url(array('page' => $this->page, 'orderBy' => Db_Attribute::IS_UNIQUE, 'direction' => (($this->orderBy == Db_Attribute::IS_UNIQUE) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('uniqueConstraint') ?>
                </a></th>
            <th><a
                        href="<?php echo $this->url(array('page' => $this->page, 'orderBy' => Db_Attribute::ORDER_NUMBER, 'direction' => (($this->orderBy == Db_Attribute::ORDER_NUMBER) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('sortingAbbreviated') ?>
                </a></th>
            <th><a
                        href="<?php echo $this->url(array('page' => $this->page, 'orderBy' => Db_Attribute::IS_ACTIVE, 'direction' => (($this->orderBy == Db_Attribute::IS_ACTIVE) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('valid') ?>
                </a></th>
            <th style="width: 300px;">&nbsp;</th>
        </tr>
        <?php
        $row_count = 0;
        foreach ($this->paginator as $item) :
            ?>
            <?php
            if (!$item[Db_Attribute::IS_ACTIVE]) {
                ?>
                <tr class="inactive">
                <?php
            } else {
                ?>


                <tr>
                <?php
            }
            ?>
            <td><a class="link"
                   href="<?php echo APPLICATION_URL . 'attribute/edit/attributeId/' . $item[Db_Attribute::ID]; ?>"><?php echo $item[Db_Attribute::NAME]; ?></a>
            </td>
            <td><?php echo $item[Db_Attribute::DESCRIPTION]; ?></td>
            <td><?php echo $item['attributeGroup']; ?></td>
            <td><?php echo $this->translate('name_' . $item['attributeTypeName']); ?></td>
            <td><?php echo(($item[Db_Attribute::IS_UNIQUE]) ? $this->translate('yes') : $this->translate('no')); ?></td>
            <td><?php echo $item[Db_Attribute::ORDER_NUMBER]; ?></td>
            <td>
                <?php echo(($item[Db_Attribute::IS_ACTIVE]) ? $this->translate('active') : $this->translate('inactive')); ?>
            </td>
            <td>
                <?php if ($item[Db_Attribute::IS_ACTIVE]) { ?>
                    <a class="delete_list"
                       href="javascript:delete_attribute(<?php echo $item[Db_Attribute::ID]; ?>);"
                       title="<?php echo $this->translate('delete') ?>"></a>
                <?php } ?>
                <div class="rfloater">

                    <?php if ($item['attributeTypeName'] == Enum_AttributeType::CI_TYPE || $item['attributeTypeName'] == Enum_AttributeType::CI_TYPE_PERSIST) { ?>
                        <a class="link buttonLink"
                           href="<?php echo APPLICATION_URL ?>attribute/ordercitypeattribute/attributeId/<?php echo $item[Db_Attribute::ID] ?>"><?php echo $this->translate('orderCiTypeAttribute') ?></a>
                    <?php } ?>
                    <a class="duplicate_list buttonLink"
                       href="<?php echo APPLICATION_URL ?>attribute/create/cloneFromId/<?php echo $item[Db_Attribute::ID] ?>" title="<?php echo $this->translate('duplicate') ?>">&nbsp;</a>
                    <a class="edit_list buttonLink"
                       href="<?php echo APPLICATION_URL . 'attribute/edit/attributeId/' . $item[Db_Attribute::ID]; ?>">&nbsp;</a>
                    <?php if (!$item[Db_Attribute::IS_ACTIVE]) { ?>
                        <a class="link"
                           href="javascript:activate_attribute(<?php echo $item[Db_Attribute::ID]; ?>);"
                           title="<?php echo $this->translate('activate') ?>"><img
                                    class="delete_list"
                                    src='<?php echo APPLICATION_URL . "images/icon/activate.png" ?>'
                                    title="<?php echo $this->translate('activate') ?>"></a>
                    <?php } ?>
                </div>
            </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?php echo $this->paginator; ?>
<?php endif; ?>