<h1 class="pageName"><?php echo $this->translate('updateTitle'); ?></h1>
<div class="numberResult">
    (<?php echo $this->translate('numberOfResults') ?> <?php echo($this->paginator->getTotalItemCount()) ?>)
</div>

<?php if (count($this->paginator)): ?>
    <table class="list" cellpadding="0" cellspacing="0" width="100%">
        <tr class="headline">
            <th><?php echo $this->translate('filename'); ?></th>
            <th><?php echo $this->translate('dateProceeded'); ?></th>
            <th><?php echo $this->translate('log'); ?></th>
            <th>&nbsp;</th>
        </tr>
        <?php
        $row_count = 0;
        foreach ($this->paginator as $item):
            ?>
            <tr>
                <td><a href="<?php echo $this->filePath . '/' . $item['file'] ?>"><?php echo $item['file']; ?></a></td>
                <td><?php echo $item['time'] ?></td>
                <td>
                    <a href="<?php echo $this->filePath . '/log/' . $item['file'] . '.log' ?>"><?php echo $this->translate('log'); ?></a>
                </td>

                <td>
                    <a class="delete_list" href="<?php echo APPLICATION_URL ?>fileimport/queue/type/idle/method/delete/file/<?php echo $item['file']; ?>"></a>
                </td>
            </tr>
        <?php endforeach; ?>

    </table>
    <?php echo $this->paginator; ?>
<?php endif; ?>