<script type="text/javascript">
    $(document).ready(function () {
        searchAttributesFunction();
    });

    function searchAttributesFunction(optionChanged) {
        if (optionChanged === 1) {
            $("#searchStringAttributes").val('');
        }                 // clear        #searchStringAttribute if the selected option is changed
        var searchedAttribute = $("#searchStringAttributes").val().toLowerCase();       // get          user input string
        var selectedOption = parseInt($('#selectBoxAttribute option:selected').val());  // get           selected option
        if (searchedAttribute !== "") {                                                   // switch       to option 'all rights' if filter is set
            selectedOption = 5; //
            $('#selectBoxAttribute').val(5);

            $(".attributeTitle").parent().addClass('disabled'); // grey
            $(".attributeTitle:contains(" + searchedAttribute + ")").parent().removeClass('disabled')

        } else {
            $(".attributeTitle:contains('" + searchedAttribute + "')").each(function (index, element) {
                var checkBox = $(element).parent().find('div.radio_group > label > input:checked').val();
                var div = $(element).parent().addClass('disabled');
                switch (selectedOption) {
                    case 1:
                        if (checkBox == 2) {
                            div.removeClass('disabled');
                        }
                        break; //read and write / optional
                    case 2:
                        if (checkBox == 1) {
                            div.removeClass('disabled');
                        }
                        break; //read / mandatory
                    case 3:
                        if (checkBox == 0) {
                            div.removeClass('disabled');
                        }
                        break; //x
                    case 4:
                        if (checkBox == 1 || checkBox == 2) {
                            div.removeClass('disabled');
                        }
                        break; //read or write / mandatory or optional
                    case 5:
                        div.removeClass('disabled');
                        break; //no filter
                    default:
                        console.log("attribute-filter: invalid option selected");
                }
            });
        }

        //sort and insert
        $(sortDivs($('.parentPermissions').find('div.child:not(.flexboxspacer)'))).each(function () {
            $(this).insertBefore($('.parentPermissions').find('div:first'));
        });

        divCounter();
    }

</script>

<fieldset>
    <h1>Filter</h1>
    <label for="attributeFilter"><?php echo $this->translate('selectRight'); ?></label>
    <select id="selectBoxAttribute" onchange="searchAttributesFunction(1);">
        <?php foreach ($this->dropdown_options_permission as $key => $value) : ?>
            <option value="<?php echo $key; ?>"
                <?php echo ($this->default_option_permission == $key) ? 'selected="selected"' : ''; ?>>
                <?php echo $value; ?>
            </option>
        <?php endforeach; ?>
    </select>
    <br>
    <br>
    <div id="filterAttributes">
        <div class="filter-box">
            <label for="searchFilterAttributes"><?php echo $this->translate('setFilter'); ?></label>
            <input id="searchStringAttributes" type="text">
            <button type='button' id="filterAttributeButton" onclick="searchAttributesFunction()">Filtern</button>
        </div>
    </div>
    <br>
    <h1><?php echo $this->translate('result'); ?></h1>
</fieldset>