<script type="text/javascript">
    function cancel() {

        window.location.href = '<?php echo APPLICATION_URL . 'reporting/index'; ?>';

    }

    function next() {
        var selected = $("#tabs").tabs("option", "active");
        var next = getNextEnabledTab(selected);
        $("#tabs").tabs({active: next});
    }

    function getNextEnabledTab(index) {
        index += 1;
        var disabled = $("#tabs").tabs("option", "disabled");
        for (var i = 0; i < disabled.length; i++) {
            if (disabled[i] == index)
                index = getNextEnabledTab(index);
        }

        return index;
    }

    function getLastEnabledTab(index) {
        index -= 1;
        var disabled = $("#tabs").tabs("option", "disabled");
        for (var i = 0; i < disabled.length; i++) {
            if (disabled[i] == index)
                index = getLastEnabledTab(index);
        }

        return index;
    }

    function back() {
        var selected = $("#tabs").tabs("option", "active");
        var last = getLastEnabledTab(selected);
        $("#tabs").tabs({active: last});
    }

    function triggerDisabled(trigger) {
        if ($("#" + trigger + "_radio-0").is(":checked")) {
            document.forms["create"][trigger].disabled = true;
        } else {
            document.forms["create"][trigger].disabled = false;
        }
    }

    function submitForm() {
        document.forms['create'].submit();
    }

    function changeDIVElement(divElement) {
        $("#tabs").tabs({active: $(divElement).index()});
    };

    function fillInputWizard(inputtype) {
        $.post("<?php echo $this->url(array('action' => 'inputwizard')); ?>/type/" + inputtype,
            function (response) {
                $("div#inputContainer").html(response);
                $("#innerTabs").tabs();
            },
            "html"
        );
    }

    $(function () {
        $("#tabs").tabs({disabled: [2, 3]}, {active: 0});
        <?php if ($this->reporting[Db_Reporting::TRIGGER] == 'time') echo '$("#tabs").tabs("enable", 3);' ?>
        <?php if ($this->reporting[Db_Reporting::TRANSPORT] == 'mail') echo '$("#tabs").tabs("enable", 2);' ?>
    });

    $(document).ready(function () {
        fillInputWizard('<?php echo $this->reporting[Db_Reporting::INPUT]; ?>');

        $("select#input").change(function () {
            $("#tabs").tabs('enable', 1);
            fillInputWizard($(this).get(0).value);
        });
        $("select#transport").change(function () {
            if ($(this).get(0).value == 'mail')
                $("#tabs").tabs('enable', 2);
            else
                $("#tabs").tabs('disable', 2);
        });
        $("select#trigger").change(function () {
            if ($(this).get(0).value == 'time')
                $("#tabs").tabs('enable', 3);
            else
                $("#tabs").tabs('disable', 3);
        });
    })

</script>

<a class="button overview" href="<?php echo APPLICATION_URL ?>reporting/index"><?php echo $this->translate('overview') ?></a>
<h1 class="pageName"><?php echo $this->translate('reportEdit') ?></h1>

<?php $step = 1; ?>
<div id="tabs">
    <ul>
        <li><a href="#fragment-<?php echo $step ?>"><span class="att_nr"><?php echo $step;
                    $step++; ?></span><span class="att_desc"><?php echo $this->translate('reportEdit') ?></span></a>
        </li>
        <li><a href="#fragment-<?php echo $step ?>"><span class="att_nr"><?php echo $step;
                    $step++; ?></span><span class="att_desc"><?php echo $this->translate('input') ?></span></a></li>
        <li><a href="#fragment-<?php echo $step ?>"><span class="att_nr"><?php echo $step;
                    $step++; ?></span><span class="att_desc"><?php echo $this->translate('transport') ?></span></a></li>
        <li><a href="#fragment-<?php echo $step ?>"><span class="att_nr"><?php echo $step;
                    $step++; ?></span><span class="att_desc"><?php echo $this->translate('trigger') ?></span></a></li>
    </ul>

    <fieldset class="create_form steps">
        <form widgetid="create" id="create" enctype="<?php echo $this->form->getEnctype() ?>" method="<?php echo $this->form->getMethod() ?>">
            <div id="fragment-1">
                <fieldset class="lordVader">
                    <table>
                        <tbody>
                        <tr>
                            <?php echo $this->form->name ?>
                            <td class="query"><em><?php echo $this->translate('reportingNameExample'); ?></em></td>
                        </tr>
                        <tr>
                            <?php echo $this->form->description ?>
                            <td class="query"><em><?php echo $this->translate('reportingDescriptionExample'); ?></em>
                            </td>
                        </tr>
                        <tr>
                            <?php echo $this->form->note ?>
                            <td class="query"><em><?php echo $this->translate('reportingNoteExample'); ?></em></td>
                        </tr>
                        <tr>
                            <?php echo $this->form->input ?>
                            <td class="query"><em><?php echo $this->translate('reportingInputExample'); ?></em></td>
                        </tr>
                        <tr>
                            <?php echo $this->form->output ?>
                            <td class="query"><em><?php echo $this->translate('reportingOutputExample'); ?></em></td>
                        </tr>
                        <tr>
                            <?php echo $this->form->transport ?>
                            <td class="query"><em><?php echo $this->translate('reportingTransportExample'); ?></em></td>
                        </tr>
                        <tr>
                            <?php echo $this->form->trigger ?>
                            <td class="query"><em><?php echo $this->translate('reportingTriggerExample'); ?></em></td>
                        </tr>
                        </tbody>
                    </table>
                </fieldset>
                <div class="buttonCon">
                    <input type="submit" class="cancel_button" value="<?php echo $this->translate('abort') ?>" onClick="javascript:cancel(); return false;">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('save') ?>" onClick="javascript:submitForm(); return false;">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('next') ?>" onClick="javascript:next(); return false;">
                </div>
            </div>
            <div id="fragment-2">
                <div id="inputContainer"></div>
                <div class="buttonCon">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('back') ?>" onClick="javascript:back(); return false;">
                    <input type="submit" class="cancel_button" value="<?php echo $this->translate('abort') ?>" onClick="javascript:cancel(); return false;">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('save') ?>" onClick="javascript:submitForm(); return false;">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('next') ?>" onClick="javascript:next(); return false;">
                </div>
            </div>
            <div id="fragment-3">
                <table>
                    <tr>
                        <?php echo $this->form->mail ?>
                        <td class="query"><em><?php echo $this->translate('reportingOutputMailExample'); ?></em></td>
                    </tr>
                    <tr>
                        <?php echo $this->form->mail_content; ?>
                    </tr>
                </table>
                <div class="buttonCon">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('back') ?>" onClick="javascript:back(); return false;">
                    <input type="submit" class="cancel_button" value="<?php echo $this->translate('abort') ?>" onClick="javascript:cancel(); return false;">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('save') ?>" onClick="javascript:submitForm(); return false;">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('next') ?>" onClick="javascript:next(); return false;">
                </div>
            </div>
            <div id="fragment-4">
                <fieldset class="lordVader">
                    <fieldset class="execution_time">
                        <div class="execution_time_part">
                            <h3><?php echo $this->translate('minutes'); ?></h3>
                            <?php echo $this->cronform->minutes_radio; ?>
                            <?php echo $this->cronform->minutes; ?>
                        </div>
                        <div class="execution_time_part">
                            <h3><?php echo $this->translate('hours'); ?></h3>
                            <?php echo $this->cronform->hours_radio; ?>
                            <?php echo $this->cronform->hours; ?>
                        </div>
                        <div class="execution_time_part">
                            <h3><?php echo $this->translate('days'); ?></h3>
                            <?php echo $this->cronform->days_radio; ?>
                            <?php echo $this->cronform->days; ?>
                        </div>
                        <div class="execution_time_part">
                            <h3><?php echo $this->translate('months'); ?></h3>
                            <?php echo $this->cronform->months_radio; ?>
                            <?php echo $this->cronform->months; ?>
                        </div>
                        <div class="execution_time_part">
                            <h3><?php echo $this->translate('weekdays'); ?></h3>
                            <?php echo $this->cronform->weekdays_radio; ?>
                            <?php echo $this->cronform->weekdays; ?>
                        </div>
                    </fieldset>
                    <div><?php echo $this->translate('reportingTriggerTimeExample'); ?></div>
                    <div class="break"></div>
                </fieldset>
                <div class="buttonCon">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('back') ?>" onClick="javascript:back(); return false;">
                    <input type="submit" class="cancel_button" value="<?php echo $this->translate('abort') ?>" onClick="javascript:cancel(); return false;">
                    <input type="submit" class="standard_button" value="<?php echo $this->translate('save') ?>" onClick="javascript:submitForm(); return false;">
                </div>
            </div>
        </form>
    </fieldset>
</div>