<script type="text/javascript">
    function delete_relationtype(relationtype_id) {
        if (confirm('<?php echo $this->translate('areYouSureDelete') ?>')) {
            window.location.href = '<?php echo APPLICATION_URL ?>relationtype/delete/relationTypeId/' + relationtype_id;
        }
    }

    function activate_relationstype(relationtype_id) {
        if (confirm('<?php echo $this->translate('areYouSureActivate') ?>')) {
            window.location.href = '<?php echo APPLICATION_URL ?>relationtype/activate/relationTypeId/' + relationtype_id;
        }
    }
</script>

<?php
$config = Zend_Registry::get('viewConfig');

$class = "link";
$pre   = "";
if ($config->ci->detail->buttons->button) {
    $class .= " button";
} else {
    $pre .= " | ";
} ?>
<div class="button_row">
    <a class="link button" href='<?php echo APPLICATION_URL ?>relationtype/edit/relationTypeId/<?php echo $this->relationtype[Db_CiRelationType::ID] ?>'><?php echo $this->translate('edit'); ?></a>
    <?php if ($this->relationtype[Db_CiRelationType::IS_ACTIVE]): ?>
        <?php echo $pre; ?>
        <a class="<?php echo $class; ?> cancel" href="javascript:delete_relationtype(<?php echo $this->relationtype[Db_CiRelationType::ID] ?>)"><?php echo $this->translate('delete'); ?></a>
    <?php else: ?>
        <?php echo $pre; ?>
        <a class="<?php echo $class; ?> activate" href="javascript:activate_relationtype(<?php echo $this->relationtype[Db_CiRelationType::ID] ?>)"><?php echo $this->translate('activate'); ?></a>
    <?php endif; ?>
    <?php echo $pre; ?>
    <a class="<?php echo $class; ?>" href="<?php echo APPLICATION_URL ?>relationtype/index"><?php echo $this->translate('overview'); ?></a>
</div>

<h1 class="pageName"><?php echo $this->translate('relationTypeDetail'); ?></h1>

<fieldset class="formContainer">
    <table>
        <tr>
            <td><strong><?php echo $this->translate('relationtypeId'); ?></strong></td>
            <td><?php echo $this->relationtype[Db_CiRelationType::ID] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('name'); ?></strong></td>
            <td><?php echo $this->relationtype[Db_CiRelationType::NAME] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('description'); ?></strong></td>
            <td><?php echo $this->relationtype[Db_CiRelationType::DESCRIPTION] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('description2'); ?></strong></td>
            <td><?php echo $this->relationtype[Db_CiRelationType::DESCRIPTION_OPTIONAL] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('note'); ?></strong></td>
            <td><?php echo $this->relationtype[Db_CiRelationType::NOTE] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('color'); ?></strong></td>
            <td><?php echo $this->relationtype[Db_CiRelationType::COLOR] ?></td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('visualizeCiType'); ?></strong></td>
            <td>
                <input type="checkbox" disabled="disabled" <?php if ($this->relationtype[Db_CiRelationType::VISUALIZE]) echo 'checked="checked"'; ?> />
            </td>
        </tr>
        <tr>
            <td><strong><?php echo $this->translate('active'); ?></strong></td>
            <td>
                <input type="checkbox" disabled="disabled" <?php if ($this->relationtype[Db_CiRelationType::IS_ACTIVE]) echo 'checked="checked"'; ?> />
            </td>
        </tr>
    </table>
    <?php if ($this->ciTypes && count($this->ciTypes) > 0) : ?>
        <fieldset class="detail_fieldset">
            <legend><strong><?php echo $this->translate('ciTypes'); ?></strong></legend>
            <ul>
                <?php foreach ($this->ciTypes as $ciType): ?>
                    <li><?php echo($ciType[Db_CiType::NAME]); ?></li>
                <?php endforeach; ?>
            </ul>
        </fieldset>
    <?php endif; ?>
</fieldset>
