<script language="JavaScript" type="text/javascript" src="<?php echo APPLICATION_URL; ?>js/filter.js"></script>
<script type="text/javascript">
    function updatePage(page) {
        <?php
        $url = $this->url(array('orderBy' => $this->orderBy, 'direction' => $this->direction, 'filter' => $this->filter, 'page' => null));
        if (!strstr($url, 'index'))
            $url .= '/index';
        ?>
        var filterDefault = 'Filter';
        if ($("#search").val() == filterDefault)
            $("#search").val('');
        document.forms['searchForm'].action = "<?php echo $url; ?>/page/" + page;
        document.forms['searchForm'].submit();
        return false;
    }

    function delete_citype(ciid) {
        if (confirm('<?php echo $this->translate("areYouSureDelete"); ?>')) {
            window.location.href = '<?php echo APPLICATION_URL ?>citype/delete/citypeId/' + ciid;
        }
    }

    function activate_citype(ciid) {
        if (confirm('<?php echo $this->translate("areYouSureActivate"); ?>')) {
            window.location.href = '<?php echo APPLICATION_URL ?>citype/activate/citypeId/' + ciid;
        }
    }
</script>

<?php
$config = Zend_Registry::get('viewConfig');

$class = "link";
if ($config->ci->detail->buttons->button) {
    $class = " button";
}

?>
<div class="button_row">
    <a class="<?php echo $class; ?> create" href="<?php echo APPLICATION_URL . 'citype/create' ?>"><?php echo $this->translate('ciTypeCreate') ?></a>
</div>
<h1 class="pageName"><?php echo $this->translate('ciTypes'); ?></h1>
<div class="numberResult">
    (<?php echo $this->translate('numberOfResults') ?> <?php echo($this->paginator->getTotalItemCount()) ?>)
</div>

<div id="filter">
    <div class="filter-box">
        <form name="<?php echo $this->escape($this->searchForm->getName()) ?>"
              action="<?php echo $this->escape($this->searchForm->getAction()) ?>"
              method="<?php echo $this->escape($this->searchForm->getMethod()) ?>">
            <?php
            echo $this->searchForm->search->setDecorators(array('Errors', array('ViewHelper', array('tag' => '<div>'))));
            echo $this->searchForm->filterButton;
            ?>
        </form>
    </div>
</div>
<div class="clearBoth" style="margin-bottom: 15px;"></div>

<?php if (count($this->paginator)): ?>
    <table class="list" cellpadding="0" cellspacing="0" width="100%">
        <tr class="headline">
            <th>
                <?php $urlDirection = ($this->direction == "ASC") ? "DESC" : "ASC"; ?>
                <a class="link" href="<?php echo $this->url(array('orderBy' => Db_CiType::NAME, 'direction' => (($this->orderBy == Db_CiType::NAME) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('name'); ?>
                </a>
            </th>
            <th>
                <a class="link" href="<?php echo $this->url(array('orderBy' => Db_CiType::DESCRIPTION, 'direction' => (($this->orderBy == Db_CiType::DESCRIPTION) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('description'); ?>
                </a>
            </th>
            <th>
                <a class="link" href="<?php echo $this->url(array('orderBy' => Db_CiType::NOTE, 'direction' => (($this->orderBy == Db_CiType::NOTE) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('note'); ?>
                </a>
            </th>
            <th>
                <a class="link" href="<?php echo $this->url(array('orderBy' => Db_CiType::ORDER_NUMBER, 'direction' => (($this->orderBy == Db_CiType::ORDER_NUMBER) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('sorting'); ?>
                </a>
            </th>
            <th>
                <a class="link" href="<?php echo $this->url(array('orderBy' => Db_CiType::IS_ACTIVE, 'direction' => (($this->orderBy == Db_CiType::IS_ACTIVE) ? $urlDirection : "ASC"), 'filter' => $this->filter)); ?>">
                    <?php echo $this->translate('valid'); ?>
                </a>
            </th>
            <th style="width:200px;">&nbsp;</th>
        </tr>

        <?php
        $row_count = 0;
        foreach ($this->paginator as $item):
            ?>
            <?php
            if (!$item[Db_CiType::IS_ACTIVE]) {
                ?>
                <tr class="inactive">
                <?php
            } else {
                ?>
                <tr>
                <?php
            }
            ?>
            <td>
                <a class="link" href='<?php echo APPLICATION_URL . "citype/edit/citypeId/" . $item[Db_CiType::ID]; ?>'><?php echo $item[Db_CiType::NAME]; ?></a>
            </td>
            <td><?php echo $item[Db_CiType::DESCRIPTION]; ?></td>
            <td><?php echo $item[Db_CiType::NOTE]; ?></td>
            <td><?php echo $item[Db_CiType::ORDER_NUMBER]; ?></td>
            <td><?php if ($item[Db_CiType::IS_ACTIVE]) {
                    echo $this->translate('active');
                } else {
                    echo $this->translate('inactive');
                } ?></td>
            <td>
                <?php if ($item[Db_CiType::IS_ACTIVE]): ?>
                    <a class="delete_list" href="#" onclick="javascript:delete_citype(<?php echo $item[Db_CiType::ID]; ?>);"></a>
                <?php endif; ?>
                <div class="rfloater">
                    <a class="duplicate_list buttonLink" href="<?php echo APPLICATION_URL ?>citype/create/cloneFromId/<?php echo $item[Db_CiType::ID] ?>" title="<?php echo $this->translate('duplicate') ?>">&nbsp;</a>
                    <a class="edit_list buttonLink" href='<?php echo APPLICATION_URL . "citype/edit/citypeId/" . $item[Db_CiType::ID]; ?>'>&nbsp;</a>
                    <?php if (!$item[Db_CiType::IS_ACTIVE]): ?>
                        <a href="#" onclick="javascript:activate_citype(<?php echo $item[Db_CiType::ID]; ?>);"><img class="delete_list" src='<?php echo APPLICATION_URL . "images/icon/activate.png" ?>' title="<?php echo $this->translate('activate') ?>"></a>
                    <?php endif; ?>
                </div>
            </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?php echo $this->paginator; ?>
<?php endif; ?>