<script type="text/javascript">
    function reset() {
        window.location.href = '<?php echo APPLICATION_URL . 'attributegroup/index'; ?>';
    }

    function submit() {
        $('#create').submit();
    }

    function next() {
        var selected = $("#tabs").tabs("option", "active");
        var next = getNextEnabledTab(selected);
        $("#tabs").tabs({active: 1});
    }

    function back() {
        var selected = $("#tabs").tabs("option", "active");
        var last = getLastEnabledTab(selected);
        $("#tabs").tabs({active: 0});
    }

    $(document).ready(function () {
        $(document).ready(function () {
            $("form#create input").keypress(function (e) {
                if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
                    submit();
                }
            });
            $("form#create select").keypress(function (e) {
                if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
                    submit();
                }
            });
        });

        $('.sortable').sortable({
            axis: 'y', update: function (event, ui) {

                var data = $(this).sortable('toArray');

                var sortAttributes = $("[id ^= sort_attribute_]");

                sortAttributes.each(function (index) {

                    var sort_elem = $(sortAttributes[index]);
                    var sort_elem_id = sort_elem.attr('id'); //console.log(sort_elem_id +": "+index);
                    var attribute_id = sort_elem_id.replace("sort_attribute_", "");
                    var input_sort_attribute_id = "input_sort_attribute_" + attribute_id;

                    $('#' + input_sort_attribute_id).val(index);
                })
            }
        });

        $("#tabs").tabs({active: 0});
    })
</script>


<div class="button_row">
    <a href="	<?php echo APPLICATION_URL ?>attributegroup/index">
        <?php echo $this->translate('overview') ?>
    </a>
</div>

<h1 class="pageName"><?php echo $this->translate('attributegroupCreate') ?></h1>

<div id="tabs">

    <ul>
        <li>
            <a href="#fragment-1">
                <span class="att_nr">1</span>
                <span class="att_desc"><?php echo $this->translate('createattributegroup') ?></span>
            </a>
        </li>
        <li>
            <a href="#fragment-2">
                <span class="att_nr">2</span>
                <span class="att_desc"><?php echo $this->translate('sortattributegroup') ?></span>
            </a>
        </li>
    </ul>

    <fieldset class="create_form steps">
        <form widgetid="create" id="create" enctype="multipart/form-data"
              method="post" dojoattachpoint="containerNode"
              dojoattachevent="onreset:_onReset,onsubmit:_onSubmit">

            <div id="fragment-1">
                <fieldset class="lordVader">
                    <table>
                        <tbody>
                        <?php
                        echo $this->form->name;
                        echo $this->form->parentAttributeGroup;
                        echo $this->form->description;
                        echo $this->form->note;
                        echo $this->form->sorting;
                        echo $this->form->duplicate_allow;
                        echo $this->form->valid;
                        ?>
                        </tbody>
                    </table>
                </fieldset>
            </div>

            <div id="fragment-2">
                <ol class="sortable" style="margin: 20px">
                    <?php foreach ($this->attributes as $element) : ?>
                        <li class="ui-state-default">
                            <input type="hidden"
                                   id="input_sort_attribute_<?php echo $element['id'] ?>"
                                   name="sort_attribute[<?php echo $element['id'] ?>]"
                                   value="<?php echo $element['order_number'] ?>" />
                            <?php if ($this->adminMode === true) : ?>
                                <div id="sort_attribute_<?php echo $element['id'] ?>">
                                    <?php echo $element['name'] ?>
                                </div>
                            <?php else : ?>
                                <div id="sort_attribute_<?php echo $element['id'] ?>">
                                    <?php echo $element['description'] ?>
                                </div>
                            <?php endif; ?>

                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
        </form>

        <div class="buttonCon">
            <input type="submit"
                   class="cancel_button"
                   value="<?php echo $this->translate('abort') ?>"
                   onClick="javascript:reset()">
            <input type="submit"
                   class="standard_button"
                   value="<?php echo $this->translate('save') ?>"
                   onClick="javacript:submit()">
        </div>
    </fieldset>
</div>
